### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thumphries** [thumphries/projector#6]
Meta-issue for things that should be done and in what order.

## Spec changes

- [ ] Integrate Machinator into the core language
    - Start by just inlining the code and parsing the files
    - Eventually data definitions will be part of the plain syntax
- [ ] Implement a real termination checker
    - Really basic. but necessary to relax the syntactic restrictions sufficiently to allow `let`
- [ ] Allow multiple definitions per file
    - Syntax change; something like `foo = \x -> x`
    - Requires decent termination checker
- [ ] Allow parameterised datatypes
- [ ] Add some notion of namespacing and remove variable name munging
    - Existing approach was to punt this to the build system / integrator, but it was a huge mistake
    - Could potentially be done via the record system; each file produces a record of functions

## Cleanup

- [ ] #2 Remove all Ambiata libraries
    - Library needs to build via cabal new-build and/or stack
    - Partially complete on the [`topic/deambiata`](https://github.com/thumphries/projector/tree/topic/deambiata) branch
- [ ] Rewrite Jack tests in Hedgehog
- [ ] Use `bound` or similar for core evaluation
    - Current implementation is completely naive and runs O(N^2) or worse
    - Copying into new representation and back will cost less than the current thing
- [ ] Sand a few hacks off the type checker (reasonably well documented in Check.hs)
